ubiquote/api/urls.py
from django.urls import path
from . import mixins, views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,

)

app_name = 'api'

urlpatterns = [
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),   
    path('token/refresh-session/', mixins.RefreshTokenView.as_view(), name='token-refresh-session'),
    
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),     
    
    path("", views.HomeQuotesAPIView.as_view(), name="home-api-view"),
    
    

    
    path("categories/", views.CategoriesAPIView.as_view(), name="categories-list-api-view"),
    path("category/<str:slug>/", views.CategoryAPIView.as_view(), name="category-api-view"),
    
    path("category/<str:slug>/quotes/", views.CategoryQuotesAPIView.as_view(), name="category-quotes-api-view"),        
    
    


    path("users/", views.UsersAPIView.as_view(), name="users-list-api-view"),    
    path("user/<str:slug>/", views.UserAPIView.as_view(), name="user-api-view"),   # User info
    
    path('user/<str:slug>/quotes/', views.UserQuotesContributorAPIView.as_view(), name='user-quotes-contributor-api-view'), # Quote with contributor is user
    
    path('likes/<str:slug>/', views.UserQuotesLikesAPIView.as_view(), name='user-quotes-likes-api-view'),   

    # CRUD operations for quotes
    path("quotes/", views.QuotesAPIView.as_view(), name="quotes-list-api-view"),
    path("quote/<int:id>/", views.QuoteAPIView.as_view(), name="quote-api-view"),    
    
    path('quote/create/', views.QuoteCreateAPIView.as_view(), name='quote-create'),
    path('quote/<int:id>/update/', views.QuoteUpdateAPIView.as_view(), name='quote-update'),
    path('quote/<int:id>/delete/', views.QuoteDeleteAPIView.as_view(), name='quote-delete'),

    # CRUD operations for authors
    path("authors/", views.AuthorsAPIView.as_view(), name="authors-list-api-view"),
    path("author/<str:slug>/", views.AuthorAPIView.as_view(), name="author-api-view"),        
    path('author/quotes/<str:slug>/', views.AuthorQuotesAPIView.as_view(), name='author-quotes-api-view'),    
    
    path('author/create/', views.AuthorCreateAPIView.as_view(), name='author-create'),
    path('author/<str:slug>/update/', views.AuthorUpdateAPIView.as_view(), name='author-update'),
    path('author/<str:slug>/delete/', views.AuthorDeleteAPIView.as_view(), name='author-delete'),
    
    # path("quote/upload-image/", views.TemporaryImageUploadView.as_view(), name="upload_temp_image"),
    
    
    # path('quote/like/<int:id>/', views.QuotesLikesAPIView.as_view(), name='like-quote'),    
    
    # path('quote/like/<int:id>/', like_quote, name='like-quote'),    
       
           
    # path('quote/<int:quote_id>/like/', LikeQuoteAPIView.as_view(), name='like-quote'),

]

ubiquote/persons/authors/urls.py
# from .views import GetAuthorsView, GetAuthorView , AddAuthorView, UpdateAuthorView , DeleteAuthorView 
from . import views

# from .views import search_authors, author_list
from django.urls import path, include, re_path, reverse

# from persons.authors.models import AuthorAutocomplete
# from .models import AuthorAutocomplete


app_name = 'authors'

urlpatterns = [
    # path('', views.home, name='home'),
    
    # url(
    #     r'^author-autocomplete/$',
    #     AuthorAutocomplete.as_view(),
    #     name='author-autocomplete',
    # ),    
    
    # path(r'^author-autocomplete/$/', views.AuthorAutocomplete.as_view(), name='author-autocomplete'),
    # path('author-autocomplete/', views.AuthorAutocomplete.as_view(), name='author-autocomplete'),    
    
    # path('search_authors/',views.search_authors, name='search_authors'),
    # path('author_list/', views.author_list, name='author_list'),      
    
    path('authors/', views.GetAuthorsView.as_view(), name='get-authors'),
    path('author/<str:slug>/', views.GetAuthorView.as_view(), name='get-author'),
    path('add/author/', views.AddAuthorView.as_view(), name='add-author'),
    path('update/author/<str:slug>/', views.UpdateAuthorView.as_view(), name='update-author'),
    path('delete/author/<str:slug>/', views.DeleteAuthorView.as_view(), name='delete-author'),
    
  
   
]

ubiquote/persons/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
  
    # path('', include('django.contrib.auth.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    # path('login/', views.ModalLoginView.as_view(), name='login'),    
    path('logout/', views.LogoutView.as_view(), name='logout'),      
    
    path('users/', views.GetUsersView.as_view(), name='get-users'),
    path('user/<str:slug>/', views.GetUserView.as_view(), name='get-user'),
      
    path('update/user/<str:slug>/', views.UpdateUserView.as_view(), name='update-user'),
    path('delete/user/<str:slug>/', views.DeleteUserView.as_view(), name='delete-user'), 
    
    
    path('likes/<str:slug>/', views.GetUserLikesView.as_view(), name='get-user-likes'),        
  
    # path('add/user/', AddUserView.as_view(), name='add-user'),       
    
]

ubiquote/texts/quotes/urls.py
from django.urls import path
from django.urls import re_path
from . import views

app_name = 'quotes'

urlpatterns = [
    
    path('quotes/', views.GetQuotesView.as_view(), name='get-quotes'),
    
    # path('<str:author_slug>/<str:slug>/', views.GetQuoteView.as_view(), name='get-quote'),
    path('quote/<str:slug>/', views.GetQuoteView.as_view(), name='get-quote'),
    
    # path('quote/<str:slug_with_id>/', views.GetQuoteView.as_view(), name='get-quote'),    
    
    
    path('add/quote/', views.AddQuoteView.as_view(), name='add-quote'),
    path('update/quote/<str:slug>/', views.UpdateQuoteView.as_view(), name='update-quote'),
    path('delete/quote/<str:slug>/', views.DeleteQuoteView.as_view(), name='delete-quote'),

    
    path('quote/like/<int:id>/', views.like_quote, name='like_quote'),  
    
    # path('<str:author_slug>/<str:slug>/img/', views.GetQuoteView.as_view(), name='get-img_quote'),    
    path('quote/<str:slug>/img/', views.GetQuoteView.as_view(), name='get-img_quote'),      
      
    # path('recommendations/<int:user_id>/', views.recommend_quotes, name='recommend-quotes'),
    
    # path('author/<str:slug>/', views.GetAuthorView.as_view(), name='author-quotes'),

]

ubiquote/texts/urls.py
from django.urls import path
from . import views

app_name = 'texts'

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.HomeView.as_view(), name='get-home'),    
    
    path('categories/', views.GetCategoriesView.as_view(), name='get-categories'),
    # path('category/<int:pk>/', GetCategoryView.as_view(), name='get-category'),
    path('category/<str:slug>/', views.GetCategoryView.as_view(), name='get-category'),
]

ubiquote/ubiquote/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

from dal import autocomplete
import djhacker
from django import forms


from persons.authors.models import AuthorAutocomplete

from texts.quotes.models import Quote
from persons.authors.models import Author

from django.utils.translation import gettext_lazy as _

app_name = 'ubiquote'



urlpatterns = []

# Optional: expose this route so users can POST lang choices manually (e.g. via a dropdown)
urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

# URLs with language prefix — language will be auto-activated
urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),

    # Include your apps — these will get `fr/`, `en/`, etc. prefixes
    re_path(r'', include('texts.urls', namespace='texts')),
    re_path(r'', include('texts.quotes.urls', namespace='quotes')),
    re_path(r'', include('persons.users.urls', namespace='users')),
    re_path(r'', include('persons.authors.urls', namespace='authors')),

    # Optional: include autocomplete if localized
    path(_('author-autocomplete/'), AuthorAutocomplete.as_view(), name='author-autocomplete'),

    # Optional: localize API routes too (only if needed)
    path(_('api/'), include("api.urls")),
)

# Optional: include rosetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls')),
    ]

# Serve media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# urlpatterns = [
#     # path('admin/', admin.site.urls),
#     path(_('admin/'), admin.site.urls),
    
#     path(_('api/'), include("api.urls")),

#     path(
#         r'author-autocomplete/',
#         AuthorAutocomplete.as_view(),
#         name='author-autocomplete',
#     ),
    

    
# ]

# urlpatterns += i18n_patterns (
#     re_path(r'', include('texts.urls', namespace='texts')),
#     re_path(r'', include('texts.quotes.urls', namespace='quotes')),
#     re_path(r'', include('persons.users.urls', namespace='users')),            
#     re_path(r'', include('persons.authors.urls', namespace='authors')),

    
# )

# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
# ]
    
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
#     import debug_toolbar
#     urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns
    

# djhacker.formfield(
#     Quote.author,
#     forms.ModelChoiceField,
#     widget=autocomplete.ModelSelect2(url='ubiquote:author-autocomplete')
#     )

ubiquote/texts/quotes/forms.py
from django import forms
from dal import autocomplete
import json

from .models import Quote, Author, QuoteRaw
from texts.models import Category
from .utils import clean_text

from .utils import generate_response
from .utils import QuoteDuplicateException

from django.utils.translation import gettext_lazy as _



class QuoteForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2(
            url='author-autocomplete',
            attrs={
                'data-html': True,
                'data-minimum-input-length': 2,
                'class': 'form-control',
            },
        )
    )
    

    def clean_categories(self):
        categories = self.cleaned_data.get('categories')
        if categories and categories.count() > 3:
            raise forms.ValidationError('You can associate a maximum of 3 categories.')
        return categories
    
    
    def clean_author(self):
        author = self.cleaned_data.get('author')
        if not author:
            try:
                return Author.objects.get(id=75)  # Your "Unknown" author
            except Author.DoesNotExist:
                raise forms.ValidationError("Default author Unknonw not found (ID 75).")
        return author
    


    def clean_text(self):
        text = self.cleaned_data['text']
        return clean_text(text, self.data.get('lang', None))  # pass lang to your clean_text function


    class Meta:
        model = Quote
        fields = ('text', 'author', 'lang', 'categories', 'status', 'contributor', 'dimensions')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': _("Put your quote here")}),
            'lang': forms.Select(attrs={'class': 'form-control'}),
            'categories': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'contributor': forms.HiddenInput(),
        }
        
        

class QuoteRawForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2(
            url='author-autocomplete',
            attrs={
                'data-html': True,
                'data-minimum-input-length': 2,
                'class': 'form-control',
            },
        )
    )


    class Meta:
        model = QuoteRaw
        fields = ('text', 'author', 'lang', 'contributor', 'processed')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': _("Put your quote here")}),
            'lang': forms.Select(attrs={'class': 'form-control'}),
            'contributor': forms.HiddenInput(),
            'processed': forms.CheckboxInput(attrs={'class': 'flag'})      
        }        

ubiquote/texts/quotes/templates/add_quote.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Add a quote" %}{% endblock %}
{% block meta_decription %}{% translate "Add a quote" %} - {% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h1>{% translate "Add a quote" %}</h1> 



        <form action="" method="POST" class="form-control"> <!--  hx-post="." --> 
            

            {% csrf_token %}
            {{ form.as_p }}

            <!-- <table style="display: none">
                {{ view.formset.empty_form }}
            </table>
    
            <table>
                {{ view.formset }}
            </table>             -->

        

            <button class="btn btn-secondary">{% translate "Post" %}</button>

        </form>

    {% else %}
        <p>You are not allowed here</p>
    {% endif %}

    {{ form.media }}
    {% include 'author_select_form_script.html' %}  


{% endblock %}  

ubiquote/texts/quotes/templates/author_select_form_script.html
<script>
    (function($) {
        $('#add-form').click(function() {
            var index = $('#id_inline_test_models-TOTAL_FORMS').val()
            var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
            newTable.find(':input').each(function() {
                for (attr of ['last_name', 'id'])
                    $(this).attr(
                        attr,
                        $(this).attr(attr).replace('__prefix__', index)
                    )
            })
            newTable.insertBefore($(this))
            $('#id_inline_test_models-TOTAL_FORMS').val(
                parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
            )
            newTable.slideDown()
        })
    })($)
    </script>  

ubiquote/texts/quotes/templates/delete_quote.html
{% extends 'base.html' %}

{% block title %}Delete a quote{% endblock %}
{% block meta_decription %}{{ quote.text }} - {% endblock %}

{% block body %}

{% if user.is_authenticated  and user.id == quote.contributor.id  or user.is_superuser %}

    <h1>Delete a quote</h1>

    <p>{{ quote.text|safe }}</p>

    <form method="POST" class="form-control"> 

        {% csrf_token %}


        <button class="btn btn-secondary" type="submit">Delete</button>

    </form>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  


    {% endblock %}  

ubiquote/texts/quotes/templates/get_quote.html
{% extends 'layout_three_column.html' %}

{% block title %}
  {{ quote.text }}
{% endblock %}
{% block meta_decription %}
  {{ quote.text }} 
{% endblock %}

{% block content %}


  {% include "snippets/previous_page.html" %}   
  
<div class="card mt-3">
{% include "quote_card.html" %}  
</div> 

{% endblock %}  

ubiquote/texts/quotes/templates/get_quotes.html
{% extends 'layout_three_column.html' %}
{% load i18n %}


{% block title %}Quotes{% endblock %}
{% block meta_decription %}All the quotes{% endblock %}




{% block content %}


{% include "partials/search_quotes.html" %}    
<div id="content">
    {% include 'partials/quotes_cards.html' %}
</div>



{% endblock %}  
</div>

ubiquote/texts/quotes/templates/img_quote.html
    <a href="{% url 'quotes:get-img_quote' quote.slug  %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="black" class="bi bi-marker-tip generate_img" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5 6.064-1.281-4.696A.5.5 0 0 0 9.736 9H6.264a.5.5 0 0 0-.483.368l-1.28 4.696A6.97 6.97 0 0 0 8 15c1.275 0 2.47-.34 3.5-.936m.873-.598a7 7 0 1 0-8.746 0l1.19-4.36a1.5 1.5 0 0 1 1.31-1.1l1.155-3.851c.213-.713 1.223-.713 1.436 0l1.156 3.851a1.5 1.5 0 0 1 1.31 1.1z"/>
</svg></a>
      

ubiquote/texts/quotes/templates/like_quote.html
{% if user.is_authenticated %}
    <form id="quote-{{ quote.id }}">
        {{ quote.likes_count|default:""}}
        {% csrf_token %}
        <button 
            hx-post="{% url 'quotes:like_quote' quote.id %}" 
            hx-swap="outerHTML" 
            hx-target="#quote-{{ quote.id }}" 
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            class="like-button bg-transparent border-0">
            {% if user.id in quote.likes or liked  %}

                <!-- User has liked, display filled heart -->
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-heart-fill " viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                </svg>
            {% else %}
                <!-- User has not liked, display empty heart -->
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="black" class="bi bi-heart like" viewBox="0 0 16 16">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                </svg>
            {% endif %}

        </button>

    </form>



{% else %}



    <form method="post" id="quote-{{ quote.id }}">
        {{ quote.likes_count}}
        {% csrf_token %}
        <button class="like-button bg-transparent border-0"
            hx-get="{% url 'users:login' %}?next={{ request.get_full_path}}"
            
            hx-target="#modal-container"
            hx-swap="innerHTML"
        >
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="black" class="bi bi-heart like" viewBox="0 0 16 16">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
            </svg>
        </button>

    </form>  


{% endif %}

ubiquote/texts/quotes/templates/pagination.html
<!-- Show pagination only if javascript is desactivated -->
<noscript> 

{% if next_page_url or previous_page_url  %}
    <div class="pagination m-md-5 align-items-center justify-content-center">
        <span class="page-links">
            {% if previous_page_url %}
                <a href="{{ previous_page_url }}">&laquo; previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_number }}
            </span>
            {% if next_page_url %}
                <a href="{{ next_page_url }}">next &raquo;</a>
            {% endif %}
        </span>
    </div>    
{% endif %} 
</noscript>

ubiquote/texts/quotes/templates/quote_card.html
{% load i18n %}
{% load highlight %}
{% load translated_author %}
{% load category_tags %}


  

    <div class="card-header" >
      {% translate "Quote" %}
    </div>
    <div class="card-body">


      <div class="container-fluid">
        <div class="row">
          <div class="col-sm">


            <blockquote class="blockquote mb-0">
              <p>
                <a href="{% url 'quotes:get-quote' quote.slug  %}" class="">{{ quote.text|highlight_search:search_query|safe }}</a>

              </p>
              {% if quote.author %}
                <p class="blockquote-footer">

                  <a href="{% url 'authors:get-author' quote.author.slug  %}" class="">

                    {% include "snippets/author_name_snippet.html" with quote=quote search_query=search_query %}
                
                  </a>

                  <!-- in <cite title="Source Title">Source Title</cite> -->
                </p>
      
              {% endif %}            
            </blockquote>
          </div>

           
        </div>
      
      </div>


    </div>
    <ul class="list-group list-group-flush">

      <li class="list-group-item">
        {% comment %}
        {% translate "categories" %} :
        {% endcomment %}   

            {% for quote_category in quote.categories %}
            <a href="{% url 'texts:get-category' quote_category.slug  %}" class="link-offset-2 link-underline link-underline-opacity-10">
              {{ quote_category|get_translated_title|highlight_search:search_query|safe }}
            </a> &nbsp;
            
            {% endfor %}

                            


            {% comment %}

            
                    
            {% for quote_category in quote.categories %}
                <a href="{% url 'texts:get-category' quote_category.slug %}" class="link-offset-2 link-underline link-underline-opacity-10">
                    {{ quote_category|translated_title|highlight_search:search_query|safe }}
                </a>&nbsp;
            {% endfor %}
                    


            {% for quote_category in quote.categories %}
              <a href="{% url 'texts:get-category' quote_category.slug %}" class="link-offset-2 link-underline link-underline-opacity-10">
                {{ quote_category.translated|default:{}|get_item:lang|default:{}|get_item:"title" }}
              </a>&nbsp;
            {% endfor %}



            {% for quote_category in quote.categories %}
              {% with quote_category.translated|get_translated as trans %}
                <a href="{% url 'texts:get-category' quote_category.slug %}" class="link-offset-2 link-underline link-underline-opacity-10">
                  {{ trans.title|default:quote_category.title }}
                </a>
              {% endwith %}
            {% endfor %}  
            
            {% endcomment %}             


      </li>
      {% comment %}
      <li class="list-group-item">
  

        <p>Polarity: {{ quote.dimensions.polarity }}</p>
        <p>Readability: {{ quote.dimensions.readability }}</p>
        <p>Emotions: 

          {% for emotion in quote.dimensions.emotions %}
          {{ emotion }} 
          {% endfor %}

      </p>
      </li>  
      {% endcomment %}      

      {% comment %}
      <li class="list-group-item">      
        {% if user.is_authenticated and user.id == quote.contributor.id %}
        <div class="float-end">                  
          <a href="{% url 'quotes:update-quote' quote.slug  %}" class="btn btn-primary x-1"> {% translate "update" %}</a>
          <a href="{% url 'quotes:delete-quote' quote.slug  %}" class="btn btn-primary x-1"> {% translate "delete" %}</a>
        </div>
        {% else %}

        {% endif %}         
        
        {% translate "published" %} {{ quote.date_created }}  {% translate "by" %} 
        <a href="{% url 'users:get-user' quote.contributor.slug  %}" class="link-offset-2 link-underline link-underline-opacity-10">
          {{ quote.contributor.username|safe }}
        </a>
      </li>
      {% endcomment %}
      <li class="list-group-item">
        <div class="float-end">

  
          
          {% include "like_quote.html" %}           
              
          {% include "img_quote.html" %} 

          {% include "share_quote.html" %} 

              
        </div>  
        
      </li>

      {% comment %}
      <!-- Display when the quote was liked on the Favorite page -->

      {% if '/likes/' in request.path %}
      <li class="list-group-item">
        <div class="cd-grid gap-2 d-md-flex justify-content-md-end">

            {% for liked_quote in liked_quotes_timestamps %}
              {% if liked_quote.quote_id == quote.id %}
                  <p>You liked this quote on: {{ liked_quote.timestamp }}</p>
              {% endif %}
            {% endfor %}
      
        </div>  
      </li>
      {% endif %}
      {% endcomment %}      



    </ul> 

ubiquote/texts/quotes/templates/quotes_pagination.html
<!-- Show pagination only if javascript is desactivated -->
<noscript> 

{% if next_page_url or previous_page_url  %}
    <div class="pagination m-md-5 align-items-center justify-content-center">
        <span class="page-links">
            {% if previous_page_url %}
                <a href="{{ previous_page_url }}">&laquo; previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_number }}
            </span>
            {% if next_page_url %}
                <a href="{{ next_page_url }}">next &raquo;</a>
            {% endif %}
        </span>
    </div>    
{% endif %} 
</noscript>

ubiquote/texts/quotes/templates/recommended_quotes.html
{% extends 'base.html' %}

{% block title %}Recommanded Quotes{% endblock %}
{% block meta_decription %}All the recommanded quotes{% endblock %}

{% load i18n %}


{% block body %}

<p>{% translate "Welcome in Extraquote" %}</p>
<p>Citations recommandées pour vous en fonction de vos likes.</p>

{% include "quotes_cards.html" %}

{% include "quotes_pagination.html" %}   





{% endblock %}  

ubiquote/texts/quotes/templates/share_quote.html
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><title>ionicons-v5-b</title><path d="M448,256,272,88v96C103.57,184,64,304.77,64,424c48.61-62.24,91.6-96,208-96v96Z" style="fill:none;stroke:#000;stroke-linejoin:round;stroke-width:32px"/></svg>

ubiquote/texts/quotes/templates/update_quote.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Edit a quote{% endblock %}
{% block meta_decription %}{{ quote.text }} - {% endblock %}

{% block body %}

    {% if user.is_authenticated %}
        <h1>Edit a quote</h1>
        
        <form action="" method="POST" class="form-control"> 

            {% csrf_token %}
            {{ form.as_p }}

            <!-- {{ form.status.as_hidden }} -->


            <table style="display: none">
                {{ view.formset.empty_form }}
            </table>

            <table>
                {{ view.formset }}
            </table>            


            <button class="btn btn-secondary">Update</button>

        </form>

    {% else %}
        <p>You are not allowed here</p>
    {% endif %}  

    {{ form.media }}
    {% include 'author_select_form_script.html' %}  

{% endblock %}  