ubiquote/api/urls.py
from django.urls import path
from . import mixins, views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,

)

app_name = 'api'

urlpatterns = [
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),   
    path('token/refresh-session/', mixins.RefreshTokenView.as_view(), name='token-refresh-session'),
    
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),     
    
    path("", views.HomeQuotesAPIView.as_view(), name="home-api-view"),
    
    

    
    path("categories/", views.CategoriesAPIView.as_view(), name="categories-list-api-view"),
    path("category/<str:slug>/", views.CategoryAPIView.as_view(), name="category-api-view"),
    
    path("category/<str:slug>/quotes/", views.CategoryQuotesAPIView.as_view(), name="category-quotes-api-view"),        
    
    


    path("users/", views.UsersAPIView.as_view(), name="users-list-api-view"),    
    path("user/<str:slug>/", views.UserAPIView.as_view(), name="user-api-view"),   # User info
    
    path('user/<str:slug>/quotes/', views.UserQuotesContributorAPIView.as_view(), name='user-quotes-contributor-api-view'), # Quote with contributor is user
    
    path('likes/<str:slug>/', views.UserQuotesLikesAPIView.as_view(), name='user-quotes-likes-api-view'),   

    # CRUD operations for quotes
    path("quotes/", views.QuotesAPIView.as_view(), name="quotes-list-api-view"),
    path("quote/<int:id>/", views.QuoteAPIView.as_view(), name="quote-api-view"),    
    
    path('quote/create/', views.QuoteCreateAPIView.as_view(), name='quote-create'),
    path('quote/<int:id>/update/', views.QuoteUpdateAPIView.as_view(), name='quote-update'),
    path('quote/<int:id>/delete/', views.QuoteDeleteAPIView.as_view(), name='quote-delete'),

    # CRUD operations for authors
    path("authors/", views.AuthorsAPIView.as_view(), name="authors-list-api-view"),
    path("author/<str:slug>/", views.AuthorAPIView.as_view(), name="author-api-view"),        
    path('author/quotes/<str:slug>/', views.AuthorQuotesAPIView.as_view(), name='author-quotes-api-view'),    
    
    path('author/create/', views.AuthorCreateAPIView.as_view(), name='author-create'),
    path('author/<str:slug>/update/', views.AuthorUpdateAPIView.as_view(), name='author-update'),
    path('author/<str:slug>/delete/', views.AuthorDeleteAPIView.as_view(), name='author-delete'),
    
    # path("quote/upload-image/", views.TemporaryImageUploadView.as_view(), name="upload_temp_image"),
    
    
    # path('quote/like/<int:id>/', views.QuotesLikesAPIView.as_view(), name='like-quote'),    
    
    # path('quote/like/<int:id>/', like_quote, name='like-quote'),    
       
           
    # path('quote/<int:quote_id>/like/', LikeQuoteAPIView.as_view(), name='like-quote'),

]

ubiquote/persons/authors/urls.py
# from .views import GetAuthorsView, GetAuthorView , AddAuthorView, UpdateAuthorView , DeleteAuthorView 
from . import views

# from .views import search_authors, author_list
from django.urls import path, include, re_path, reverse

# from persons.authors.models import AuthorAutocomplete
# from .models import AuthorAutocomplete


app_name = 'authors'

urlpatterns = [
    # path('', views.home, name='home'),
    
    # url(
    #     r'^author-autocomplete/$',
    #     AuthorAutocomplete.as_view(),
    #     name='author-autocomplete',
    # ),    
    
    # path(r'^author-autocomplete/$/', views.AuthorAutocomplete.as_view(), name='author-autocomplete'),
    # path('author-autocomplete/', views.AuthorAutocomplete.as_view(), name='author-autocomplete'),    
    
    # path('search_authors/',views.search_authors, name='search_authors'),
    # path('author_list/', views.author_list, name='author_list'),      
    
    path('authors/', views.GetAuthorsView.as_view(), name='get-authors'),
    path('author/<str:slug>/', views.GetAuthorView.as_view(), name='get-author'),
    path('add/author/', views.AddAuthorView.as_view(), name='add-author'),
    path('update/author/<str:slug>/', views.UpdateAuthorView.as_view(), name='update-author'),
    path('delete/author/<str:slug>/', views.DeleteAuthorView.as_view(), name='delete-author'),
    
  
   
]

ubiquote/persons/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
  
    # path('', include('django.contrib.auth.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    # path('login/', views.ModalLoginView.as_view(), name='login'),    
    path('logout/', views.LogoutView.as_view(), name='logout'),      
    
    path('users/', views.GetUsersView.as_view(), name='get-users'),
    path('user/<str:slug>/', views.GetUserView.as_view(), name='get-user'),
      
    path('update/user/<str:slug>/', views.UpdateUserView.as_view(), name='update-user'),
    path('delete/user/<str:slug>/', views.DeleteUserView.as_view(), name='delete-user'), 
    
    
    path('likes/<str:slug>/', views.GetUserLikesView.as_view(), name='get-user-likes'),        
  
    # path('add/user/', AddUserView.as_view(), name='add-user'),       
    
]

ubiquote/texts/quotes/urls.py
from django.urls import path
from django.urls import re_path
from . import views

app_name = 'quotes'

urlpatterns = [
    
    path('quotes/', views.GetQuotesView.as_view(), name='get-quotes'),
    
    # path('<str:author_slug>/<str:slug>/', views.GetQuoteView.as_view(), name='get-quote'),
    path('quote/<str:slug>/', views.GetQuoteView.as_view(), name='get-quote'),
    
    # path('quote/<str:slug_with_id>/', views.GetQuoteView.as_view(), name='get-quote'),    
    
    
    path('add/quote/', views.AddQuoteView.as_view(), name='add-quote'),
    path('update/quote/<str:slug>/', views.UpdateQuoteView.as_view(), name='update-quote'),
    path('delete/quote/<str:slug>/', views.DeleteQuoteView.as_view(), name='delete-quote'),

    
    path('quote/like/<int:id>/', views.like_quote, name='like_quote'),  
    
    # path('<str:author_slug>/<str:slug>/img/', views.GetQuoteView.as_view(), name='get-img_quote'),    
    path('quote/<str:slug>/img/', views.GetQuoteView.as_view(), name='get-img_quote'),      
      
    # path('recommendations/<int:user_id>/', views.recommend_quotes, name='recommend-quotes'),
    
    # path('author/<str:slug>/', views.GetAuthorView.as_view(), name='author-quotes'),

]

ubiquote/texts/urls.py
from django.urls import path
from . import views

app_name = 'texts'

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.HomeView.as_view(), name='get-home'),    
    
    path('categories/', views.GetCategoriesView.as_view(), name='get-categories'),
    # path('category/<int:pk>/', GetCategoryView.as_view(), name='get-category'),
    path('category/<str:slug>/', views.GetCategoryView.as_view(), name='get-category'),
]

ubiquote/ubiquote/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

from dal import autocomplete
import djhacker
from django import forms


from persons.authors.models import AuthorAutocomplete

from texts.quotes.models import Quote
from persons.authors.models import Author

from django.utils.translation import gettext_lazy as _

app_name = 'ubiquote'



urlpatterns = []

# Optional: expose this route so users can POST lang choices manually (e.g. via a dropdown)
urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

# URLs with language prefix — language will be auto-activated
urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),

    # Include your apps — these will get `fr/`, `en/`, etc. prefixes
    re_path(r'', include('texts.urls', namespace='texts')),
    re_path(r'', include('texts.quotes.urls', namespace='quotes')),
    re_path(r'', include('persons.users.urls', namespace='users')),
    re_path(r'', include('persons.authors.urls', namespace='authors')),

    # Optional: include autocomplete if localized
    path(_('author-autocomplete/'), AuthorAutocomplete.as_view(), name='author-autocomplete'),

    # Optional: localize API routes too (only if needed)
    path(_('api/'), include("api.urls")),
)

# Optional: include rosetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls')),
    ]

# Serve media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# urlpatterns = [
#     # path('admin/', admin.site.urls),
#     path(_('admin/'), admin.site.urls),
    
#     path(_('api/'), include("api.urls")),

#     path(
#         r'author-autocomplete/',
#         AuthorAutocomplete.as_view(),
#         name='author-autocomplete',
#     ),
    

    
# ]

# urlpatterns += i18n_patterns (
#     re_path(r'', include('texts.urls', namespace='texts')),
#     re_path(r'', include('texts.quotes.urls', namespace='quotes')),
#     re_path(r'', include('persons.users.urls', namespace='users')),            
#     re_path(r'', include('persons.authors.urls', namespace='authors')),

    
# )

# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
# ]
    
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
#     import debug_toolbar
#     urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns
    

# djhacker.formfield(
#     Quote.author,
#     forms.ModelChoiceField,
#     widget=autocomplete.ModelSelect2(url='ubiquote:author-autocomplete')
#     )

ubiquote/texts/views.py
import random
from django.shortcuts import render
from django.contrib.auth import logout

from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate
from django.db.models import Count, Prefetch

from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, Http404

from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404

from .models import Category
from texts.quotes.models import Quote, QuotesLikes, UserQuoteRecommendation

from django.views.generic import ListView, DetailView  # CreateView, UpdateView, DeleteView
from api.mixins import QuotesFetchingMixin #, TokenRefreshMixin 

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.conf import settings
# LANGUAGES = settings.LANGUAGES
from django.utils.translation import get_language

import requests

from rest_framework.permissions import AllowAny


from django.db.models import F

# from texts.quotes.services import RecommendationService


class GetCategoriesView(QuotesFetchingMixin, ListView):
    template_name = 'get_categories.html'
    context_object_name = 'categories'  
    paginate_by = settings.DEFAULT_PAGINATION 
    api_url = 'http://127.0.0.1:8000/api/'
    

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return context
    

    def get(self, request, *args, **kwargs):
        page_number = request.GET.get('page', 1)
        search_query = request.GET.get('q', '')
        
        
        lang = get_language()
        
        api_url = f'{self.api_url}categories/?page={page_number}&q={search_query}&lang={lang}'
        response = requests.get(api_url)

        if response.status_code == 200:
            data = response.json()  
            categories = data.get('results', [])
            count = data.get('count')   
            # count = data.get('count', 0)            
            next_page_url = data.get('next')
            
        else:
            categories = []
            count = 0            
            # next_page_url = None

        context = {
            'categories': categories,
            'count': count,            
        }
        
        # print("Fetching from:", api_url)

        return render(request, self.template_name, context)
        



class GetCategoryView(QuotesFetchingMixin, ListView):
    template_name = 'get_category.html'
    # api_url = settings.API_URL


    def get(self, request, *args, **kwargs):
        page_number = request.GET.get('page', 1)
        category_slug = self.kwargs['slug']
        search_query = request.GET.get('q', '') 
        
        # Default to computed start_index if not passed from HTMX
        incoming_start_index = request.GET.get('start_index')
        if incoming_start_index is not None:
            start_index = int(incoming_start_index)
        else:
            # Only for first page or full render
            start_index = 0                     

        # Fetch quotes of the author
        quotes_data = self.get_api_data(page_number, endpoint=f'category/{category_slug}/quotes/')
        category_data = self.get_api_data(page_number, endpoint=f'category/{category_slug}/')


        # Handle pagination for quotes
        quotes = quotes_data.get('results', [])
        next_page_url = quotes_data.get('next')
        previous_page_url = quotes_data.get('previous')
        count = quotes_data.get('count', 0)

        # overide url generation to fit this special case
        lang = request.LANGUAGE_CODE        
        if next_page_url:
            next_page_url = next_page_url.replace(f'/api/category/{category_slug}/quotes/', f'/{lang}/category/{category_slug}/')

        if previous_page_url:
            previous_page_url = previous_page_url.replace(f'/api/category/{category_slug}/quotes/', f'/{lang}/category/{category_slug}/')    

        context = {
            'category': category_data,
            'quotes': quotes,
            'count': count,
            'start_index': start_index,             
            'page_number': page_number,
            'next_page_url': next_page_url,
            'previous_page_url': previous_page_url,
            'search_query': search_query,
            
        }
        return self.render_htmx_or_full_quotes(request, context)



class HomeView(QuotesFetchingMixin, ListView):
    template_name = 'home.html'
    # api_url = settings.API_URL
    

    def get(self, request, *args, **kwargs):
        
        if request.user.is_authenticated:

            
            page_number = request.GET.get('page', 1)
            search_query = request.GET.get('q', '')
            user = request.user

            # request.session.flush()
            
            # Default to computed start_index if not passed from HTMX
            incoming_start_index = request.GET.get('start_index')
            if incoming_start_index is not None:
                start_index = int(incoming_start_index)
            else:
                # Only for first page or full render
                start_index = 0           
            
     

            # Fetch data for the home view (e.g., recommendations)
            data = self.get_api_data(page_number, endpoint='')  # Custom endpoint for HomeView
            
            # print(data)
            

            # Handle pagination and results
            results = data.get('results', [])
            next_page_url, previous_page_url = self.process_pagination(data, request)
            count = data.get('count', 0)
            
            

            context = {
                'quotes': results,  # Keep this as 'quotes' if your template expects it
                'count': count,
                'start_index': start_index,
                'page_number': page_number,
                'next_page_url': next_page_url,
                'previous_page_url': previous_page_url,
                'search_query' : search_query,
            }
            
            # redirect to landing page if count ==0 (means the session is over)
            if count==0:
                logout(self.request)
                return self.render_landing_page(request) 
            
            return self.render_htmx_or_full_quotes(request, context)
        else:              
            return self.render_landing_page(request) 
  
    
    def render_landing_page(self, request):
        """Renders a public landing page for non-authenticated users."""
        return render(request, 'landing_page.html', {})  # Create `landing.html`    


# def translate(language):
#   cur_language = get_language()
#   try:
#     activate(language)
#     text = _('hello')
#   finally:
#     activate(cur_language)
#   return text
  

# # https://stackoverflow.com/a/66271685
# def get_nationality():
#   nat = Author.objects.get(id=1)
#   return _(nat.nationality)

ubiquote/texts/templates/add_quote.html
{% extends 'base.html' %}

{% block title %}Add a quote{% endblock %}
{% block meta_decription %}{{ quote.text }} - {% endblock %}

{% block body %}

    <h1>Add a quote</h1>


    <form method="POST" class="form-control"> 

        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-secondary">Post</button>

    </form>



    {% endblock %}  

ubiquote/texts/templates/delete_quote.html
{% extends 'base.html' %}

{% block title %}Delete a quote{% endblock %}
{% block meta_decription %}{{ quote.text }} - {% endblock %}

{% block body %}

    <h1>Delete a quote</h1>

    <p>{{ quote.text }}</p>

    <form method="POST" class="form-control"> 

        {% csrf_token %}


        <button class="btn btn-secondary">Delete</button>

    </form>



    {% endblock %}  

ubiquote/texts/templates/footer.html
<footer class="text-center">&copy; 2025 Ubiquote. All rights reserved.</footer>

ubiquote/texts/templates/get_categories.html
{% extends 'layout_three_column.html' %}

{% load category_tags %}


{% block title %}Categorys{% endblock %}
{% block meta_decription %}The best quote listing{% endblock %}

{% block content %}
    <h1>Categories</h1>
    <p>{{ count }} categories available in the database</p>
    <ul class="list-group col-md">
    {% for category in categories %}
    <li class="list-group-item">
      <a href="{% url 'texts:get-category' category.title|slugify  %}" class="link-offset-2 link-underline link-underline-opacity-10">
        {{ category|get_translated_title|slice:":200"|safe }} - ({{ category.quotes_count|default:"0" }} quotes)</a>

    </li>      
    {% endfor %}
    </ul>



    {% endblock %}  

ubiquote/texts/templates/get_category.html
{% extends 'layout_three_column.html' %}
{% load category_tags %}

{% block title %}{{ category.title  }}{% endblock %}

{% block meta_decription %} {{ category.title  }}- {{ category.text  }}{% endblock %}

{% block content %}

    <h1>{{ category|get_translated_title  }}</h1>
    <h4>{{ category|get_translated_text|safe  }}</h4>    
 

    <p>{{ count }} quotes in   {{  category.title }}</p>  

    {% include "partials/quotes_cards.html" %}    

{% endblock %}  

ubiquote/texts/templates/get_quote.html
{% extends 'base.html' %}
{% block title %}Ubiquote Homepage{% endblock %}

{% block meta_decription %}{{ quote.text }} - {% endblock %}

{% block body %}

    <h1>"{{ quote.text }}"</h1>

    <h2>Author :
      {% if quote.author.nickname is not None %}
        {{ quote.author.nickname|default_if_none:"" }}
      {% else %}
        {{ quote.author.first_name|default_if_none:""  }} {{ quote.author.middle_name|default_if_none:"" }} {{ quote.author.last_name|default_if_none:"" }}
      {% endif %}
    </h2>

    <h3>Contribor : {{ quote.contributor.email }}</h3>

    <!-- <p><a href="{% url 'texts:get-quotes' %}" ">Home</a></p> -->

    <p>
      <a href="{% url 'texts:update-quote' quote.id  %}" type="button" class="btn btn-info mx-2">update</a>
      <a href="{% url 'texts:delete-quote' quote.id  %}" type="button" class="btn btn-info mx-2">delete</a>
    </p>


    {% endblock %}  

ubiquote/texts/templates/home.html
{% extends 'layout_three_column.html' %}
{% load i18n %}

{% block title %}Ubiquote Homepage{% endblock %}
{% block meta_decription %}The best quote listing{% endblock %}


{% block content %}

    <!-- <h1>{{ count }} recommandations for you !</h1> -->

    <h5>{{ count }} recommandations for you !</h5>

    {% include "partials/quotes_cards.html" %}



{% endblock %}  

ubiquote/texts/templates/layout_one_column.html
<!-- templates/layout_one_column.html -->
{% extends "base.html" %}

{% block layout %}


    <!-- Main Content -->
    <main class="mx-auto">
        {% block content %}{% endblock %}

        {% comment %}
        <!-- Optional demi-page ad -->
        {% block demi_ad %}
        <div class="my-4">
            {% include "ads/demi-page.html" %}
        </div>
        {% endblock %}
        {% endcomment %}
    </main>



{% endblock %}

ubiquote/texts/templates/layout_three_column.html
<!-- templates/layout_three_column.html -->
{% extends "base.html" %}

{% block layout %}

    <div class="row">
        <!-- Left Skyscraper -->
        {% include "ads/skyscraper.html" %}


        <!-- Main Content -->
        <main class="col-md-8 col-12">

            {% comment %}
            <!-- Mobile Top Banner -->
            <div class="mobile-only mb-3">
                {% include "ads/banner.html" %}
            </div>
            {% endcomment %}            

            {% block content %}{% endblock %}

            <!-- Optional demi-page ad -->
            {% block demi_ad %}{% endblock %}
        </main>

        <!-- Right Skyscraper -->
        {% include "ads/skyscraper.html" %}
    </div>

 

{% endblock %}

ubiquote/texts/templates/nav.html
<!-- {% load i18n %} -->




{% url 'texts:get-home' as home %}

{% url 'quotes:get-quotes' as quotes %}
{% url 'quotes:add-quote' as add_quote %}
{% url 'authors:get-authors' as authors %}
{% url 'authors:get-author' author.slug as author_url %}
{% url 'texts:get-categories' as categories %}
{% url 'users:get-users' as users %}
{% url 'users:user-register' as register %}
{% url 'users:user-login' as login %}
{% url 'users:get-user-likes' user.slug as get_likes %}

{% url 'users:get-user' user.slug as user_connected %}





<nav id="nav_search_sticky">


  <ul class="nav nav-tabs ">

      <li class="nav-item">
        <a class="nav-link {% if request.path == home %}active{% endif %}"  aria-current="page" href="{% url 'texts:get-home' %}" ><i class="fa fa-fw fa-home"></i><span>{% translate "Home" %}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == quotes %}active{% endif %}" href="{% url 'quotes:get-quotes' %}"><i class="fa fa-fw fa-search"></i><span>{% translate "Quotes" %}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == authors %}active{% endif %}" href="{% url 'authors:get-authors' %}"><i class="fa fa-fw  fa-address-book-o"></i><span>{% translate "Authors" %}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == categories %}active{% endif %}" href="{% url 'texts:get-categories' %}"><i class="fa fa-fw fa-tags"></i><span>{% translate "Categories" %}</span></a>
      </li>


      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == get_likes %}active{% endif %}" href="{% url 'users:get-user-likes' user.slug  %}"><i class="fa fa-fw fa-heart"></i><span>{% translate "Likes" %}</span></a>
        </li>
        

      <li class="nav-item">
        <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button type="submit" class="nav-link" ><i class="fa fa-fw fa-sign-out"></i><span></span>{% translate "Logout" %}</span></button>
        </form>


      </li>      
      {% else %}
      <li class="nav-item">

<!-- <form method="post"> -->

          <button
    class="nav-link"
    hx-get="{% url 'users:login' %}?next={{ request.get_full_path}}"
    hx-target="#modal-container"
    hx-swap="innerHTML"
          >
          <i class="fa fa-fw fa-sign-in"></i><span>{% translate "Login" %}</span>

          
          </button>
<!-- </form>           -->


      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == register %}active{% endif %}" href="{% url 'users:register' %}"><i class="fa fa-fw fa-sign-out"></i><span>{% translate "Register" %}</span></a>
      </li>      
      {% endif %}        

      {% comment %}
      <li class="nav-item">
        <a class="nav-link {% if request.path == add_quote %}active{% endif %}" href="{% url 'quotes:add-quote' %}"><i class="fa fa-fw fa-pencil-square-o"></i><span>{% translate "Add Quote" %}</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link {% if request.path == users %}active{% endif %}" href="{% url 'users:get-users' %}"><i class="fa fa-fw fa-users"></i><span>{% translate "Users" %}</span></a>
      </li>

      {% if user.is_authenticated %} 
      <li class="nav-item">
        <a class="nav-link {% if request.path == get_likes %}active{% endif %}" href="{% url 'users:get-user-likes' user.slug  %}"><i class="fa fa-fw fa-heart"></i><span>{% translate "Likes" %}</span></a>
      </li>      
      {% else %}

      {% endif %}

      <!-- <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->

       


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-fw fa-user"></i><span>Profil</span>
        </a>

        <ul class="dropdown-menu">

          {% if user.is_authenticated %}
          <!-- <li class="nav-item">
            <a class="nav-link {% if request.path == add_quote %}active{% endif %}" href="{% url 'quotes:add-quote' %}"><i class="fa fa-fw fa-pencil-square-o"></i><span>{% translate "Add Quote" %}</span></a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link {% if request.path == get_likes %}active{% endif %}" href="{% url 'users:get-user-likes' user.slug  %}"><i class="fa fa-fw fa-heart"></i><span>{% translate "Likes" %}</span></a>
          </li>
    
            <li class="nav-item">
              <a class="nav-link {% if request.path == user_connected %}active{% endif %}" href="{% url 'users:get-user' user.slug  %}"><i class="fa fa-fw fa-user"></i><span>{{ user }}</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}"><i class="fa fa-fw fa-sign-out"></i><span>{% translate "Logout" %}</span></a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == login %}active{% endif %}" href="{% url 'users:login' %}"><span>{% translate "Login" %}</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == register %}active{% endif %}" href="{% url 'users:user-register' %}"><span>{% translate "Register" %}</span></a>
            </li>
          {% endif %}     


          <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-fw fa-language"></i><span>{% translate "Languages" %}</span>
            </a>
    
    
            {% get_current_language as current_language %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
    
            <ul class="dropdown-menu dropdown-submenu">
              {% for lang in languages %}
              <li>
                <a class="dropdown-item" href="{% if request.path|slice:'3:' != lang.code|default:'' %}/{{ lang.code }}{% endif %}{{ request.path|slice:'3:' }}">
                  {{ lang.name_local|lower }}
                </a>
              </li>
            {% endfor %}
              <!-- <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li> -->
            </ul>
          </li>

      {% endcomment %}                


        </ul>


      </li>






    </ul>








</nav>