ubiquote/api/urls.py
from django.urls import path
from . import mixins, views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,

)

app_name = 'api'

urlpatterns = [
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),   
    path('token/refresh-session/', mixins.RefreshTokenView.as_view(), name='token-refresh-session'),
    
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),     
    
    path("", views.HomeQuotesAPIView.as_view(), name="home-api-view"),
    
    

    
    path("categories/", views.CategoriesAPIView.as_view(), name="categories-list-api-view"),
    path("category/<str:slug>/", views.CategoryAPIView.as_view(), name="category-api-view"),
    
    path("category/<str:slug>/quotes/", views.CategoryQuotesAPIView.as_view(), name="category-quotes-api-view"),        
    
    


    path("users/", views.UsersAPIView.as_view(), name="users-list-api-view"),    
    path("user/<str:slug>/", views.UserAPIView.as_view(), name="user-api-view"),   # User info
    
    path('user/<str:slug>/quotes/', views.UserQuotesContributorAPIView.as_view(), name='user-quotes-contributor-api-view'), # Quote with contributor is user
    
    path('likes/<str:slug>/', views.UserQuotesLikesAPIView.as_view(), name='user-quotes-likes-api-view'),   

    # CRUD operations for quotes
    path("quotes/", views.QuotesAPIView.as_view(), name="quotes-list-api-view"),
    path("quote/<int:id>/", views.QuoteAPIView.as_view(), name="quote-api-view"),    
    
    path('quote/create/', views.QuoteCreateAPIView.as_view(), name='quote-create'),
    path('quote/<int:id>/update/', views.QuoteUpdateAPIView.as_view(), name='quote-update'),
    path('quote/<int:id>/delete/', views.QuoteDeleteAPIView.as_view(), name='quote-delete'),

    # CRUD operations for authors
    path("authors/", views.AuthorsAPIView.as_view(), name="authors-list-api-view"),
    path("author/<str:slug>/", views.AuthorAPIView.as_view(), name="author-api-view"),        
    path('author/quotes/<str:slug>/', views.AuthorQuotesAPIView.as_view(), name='author-quotes-api-view'),    
    
    path('author/create/', views.AuthorCreateAPIView.as_view(), name='author-create'),
    path('author/<str:slug>/update/', views.AuthorUpdateAPIView.as_view(), name='author-update'),
    path('author/<str:slug>/delete/', views.AuthorDeleteAPIView.as_view(), name='author-delete'),
    
    # path("quote/upload-image/", views.TemporaryImageUploadView.as_view(), name="upload_temp_image"),
    
    
    # path('quote/like/<int:id>/', views.QuotesLikesAPIView.as_view(), name='like-quote'),    
    
    # path('quote/like/<int:id>/', like_quote, name='like-quote'),    
       
           
    # path('quote/<int:quote_id>/like/', LikeQuoteAPIView.as_view(), name='like-quote'),

]

ubiquote/persons/authors/urls.py
# from .views import GetAuthorsView, GetAuthorView , AddAuthorView, UpdateAuthorView , DeleteAuthorView 
from . import views

# from .views import search_authors, author_list
from django.urls import path, include, re_path, reverse

# from persons.authors.models import AuthorAutocomplete
# from .models import AuthorAutocomplete


app_name = 'authors'

urlpatterns = [
    # path('', views.home, name='home'),
    
    # url(
    #     r'^author-autocomplete/$',
    #     AuthorAutocomplete.as_view(),
    #     name='author-autocomplete',
    # ),    
    
    # path(r'^author-autocomplete/$/', views.AuthorAutocomplete.as_view(), name='author-autocomplete'),
    # path('author-autocomplete/', views.AuthorAutocomplete.as_view(), name='author-autocomplete'),    
    
    # path('search_authors/',views.search_authors, name='search_authors'),
    # path('author_list/', views.author_list, name='author_list'),      
    
    path('authors/', views.GetAuthorsView.as_view(), name='get-authors'),
    path('author/<str:slug>/', views.GetAuthorView.as_view(), name='get-author'),
    path('add/author/', views.AddAuthorView.as_view(), name='add-author'),
    path('update/author/<str:slug>/', views.UpdateAuthorView.as_view(), name='update-author'),
    path('delete/author/<str:slug>/', views.DeleteAuthorView.as_view(), name='delete-author'),
    
  
   
]

ubiquote/ubiquote/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

from dal import autocomplete
import djhacker
from django import forms


from persons.authors.models import AuthorAutocomplete

from texts.quotes.models import Quote
from persons.authors.models import Author

from django.utils.translation import gettext_lazy as _

app_name = 'ubiquote'



urlpatterns = []

# Optional: expose this route so users can POST lang choices manually (e.g. via a dropdown)
urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

# URLs with language prefix — language will be auto-activated
urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),

    # Include your apps — these will get `fr/`, `en/`, etc. prefixes
    re_path(r'', include('texts.urls', namespace='texts')),
    re_path(r'', include('texts.quotes.urls', namespace='quotes')),
    re_path(r'', include('persons.users.urls', namespace='users')),
    re_path(r'', include('persons.authors.urls', namespace='authors')),

    # Optional: include autocomplete if localized
    path(_('author-autocomplete/'), AuthorAutocomplete.as_view(), name='author-autocomplete'),

    # Optional: localize API routes too (only if needed)
    path(_('api/'), include("api.urls")),
)

# Optional: include rosetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls')),
    ]

# Serve media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# urlpatterns = [
#     # path('admin/', admin.site.urls),
#     path(_('admin/'), admin.site.urls),
    
#     path(_('api/'), include("api.urls")),

#     path(
#         r'author-autocomplete/',
#         AuthorAutocomplete.as_view(),
#         name='author-autocomplete',
#     ),
    

    
# ]

# urlpatterns += i18n_patterns (
#     re_path(r'', include('texts.urls', namespace='texts')),
#     re_path(r'', include('texts.quotes.urls', namespace='quotes')),
#     re_path(r'', include('persons.users.urls', namespace='users')),            
#     re_path(r'', include('persons.authors.urls', namespace='authors')),

    
# )

# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
# ]
    
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
#     import debug_toolbar
#     urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns
    

# djhacker.formfield(
#     Quote.author,
#     forms.ModelChoiceField,
#     widget=autocomplete.ModelSelect2(url='ubiquote:author-autocomplete')
#     )

ubiquote/persons/authors/views.py
from django.shortcuts import render, get_object_or_404, redirect

import requests
import re
from django.utils.safestring import mark_safe

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy

from .models import Author, AuthorTranslation
from .forms import AuthorForm
from .forms import AuthorAutoCompleteForm
# from texts.quotes.views import BaseQuoteAPIListView

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# from persons.authors.models import AuthorAutocomplete

from texts.quotes.models import Quote, QuotesLikes
from texts.quotes.forms import QuoteForm
# from texts.quotes.views import LanguageFilterMixin

from api.mixins import QuotesFetchingMixin #, TokenRefreshMixin #AuthorQuoteMixin  

# from texts.quotes.views import get_user_quotes_likes

from django.db.models import Q

from django.contrib.postgres.search import SearchVector, TrigramSimilarity
from django.contrib.postgres.lookups import Unaccent

from flexidate import parse
from django.conf import settings
# LANGUAGES = settings.LANGUAGES
from django.utils.translation import get_language

from operator import itemgetter
from django.template.loader import render_to_string

from django.contrib import messages
import logging

from django.utils import translation

logger = logging.getLogger(__name__)


class GetAuthorsView(QuotesFetchingMixin, ListView):
    template_name = 'get_authors.html'
    # api_url = settings.API_URL
    

    def get(self, request, *args, **kwargs):
        page_number = request.GET.get('page', 1)
        search_query = request.GET.get('q', '')        

        # Fetch data for the home view (e.g., recommendations)
        data = self.get_api_data(page_number, endpoint='authors/', search_query=search_query)  # Custom endpoint for GetAuthorsView

        # Handle pagination and results
        authors = data.get('results', [])
        next_page_url, previous_page_url = self.process_pagination(data, request)
        count = data.get('count', 0)


        # if search_query:
        #     escaped_query = re.escape(search_query)
        #     for author in authors:
        #         author['highlighted_name'] = re.sub(
        #             f'({escaped_query})', 
        #             r'(<strong>\1</strong>)', 
        #             author['fullname'], 
        #             flags=re.IGNORECASE
        #         )
        #         author['highlighted_name'] = mark_safe(author['highlighted_name'])
        # else:
        #     for author in authors:
        #         author['highlighted_name'] = author['fullname']

        context = {
            'authors': authors,  
            'count': count,
            'page_number': page_number,
            'next_page_url': next_page_url,
            'previous_page_url': previous_page_url,
            'search_query': search_query,
        }
        return self.render_htmx_or_full_authors(request, context)
    

    
#     # Deal if javascript off
#     def render_to_response(self, context, **response_kwargs):
#         if request.htmx:
#             authors_html = render_to_string('author_list.html', context)
#             # print(authors_html)
#             return JsonResponse({'authors_html': authors_html})
#         else:
#             return super().render_to_response(context, **response_kwargs)



class GetAuthorView(QuotesFetchingMixin, ListView):
    template_name = 'get_author.html'
    # api_url = settings.ROOT_URL
    
    print(translation.get_language() )
    
    def get(self, request, *args, **kwargs):
        page_number = request.GET.get('page', 1)
        author_slug = self.kwargs.get('slug')
        search_query = request.GET.get('q', '')
        
        # Default to computed start_index if not passed from HTMX
        incoming_start_index = request.GET.get('start_index')
        if incoming_start_index is not None:
            start_index = int(incoming_start_index)
        else:
            # Only for first page or full render
            start_index = 0             

        if not author_slug:
            messages.error(request, "Author not found.")
            return redirect('authors:get-authors')

        try:
            # First try to get author data
            author_data = self.get_api_data(page_number=0, endpoint=f'author/{author_slug}/')
            # print(author_data.keys())
            
            if not author_data or isinstance(author_data, dict) and 'detail' in author_data:
                messages.error(request, "Author not found.")
                return redirect('authors:get-authors')
            
            


            # Only fetch quotes if we have valid author data
            quotes_data = self.get_api_data(page_number, endpoint=f'author/quotes/{author_slug}/')
            
            # Handle pagination for quotes
            quotes = quotes_data.get('results', [])
            next_page_url = quotes_data.get('next')
            previous_page_url = quotes_data.get('previous')
            count = quotes_data.get('count', 0)
            
            # Override url generation to fit this special case
            lang = request.LANGUAGE_CODE
            if next_page_url:
                next_page_url = next_page_url.replace(f'/api/author/quotes/{author_slug}/', f'/{lang}/author/{author_slug}/')
            if previous_page_url:
                previous_page_url = previous_page_url.replace(f'/api/author/quotes/{author_slug}/', f'/{lang}/author/{author_slug}/')    

            context = {
                'author': author_data,
                'quotes': quotes,
                'count': count,
                'start_index': start_index,                   
                'page_number': page_number,
                'next_page_url': next_page_url,
                'previous_page_url': previous_page_url,
                'search_query': search_query,
            }
            
            return self.render_htmx_or_full_quotes(request, context)
            
        except Exception as e:
            logger.error(f"Error fetching author data: {str(e)}")
            messages.error(request, "An error occurred while fetching author data.")
            return redirect('authors:get-authors')

# class GetAuthorView(AuthorQuoteMixin, ListView):
#     template_name = 'quotes/author_quotes.html'

#     def get(self, request, *args, **kwargs):
#         page_number = request.GET.get('page', 1)
#         author_slug = self.kwargs.get('slug')
#         search_query = request.GET.get('q', '')
#         incoming_start_index = request.GET.get('start_index')

#         start_index = int(incoming_start_index) if incoming_start_index else 0

#         if not author_slug:
#             messages.error(request, "Author not found.")
#             return redirect('authors:get-authors')

#         try:
#             author_data = self.fetch_author_data(author_slug)
#             if not author_data:
#                 messages.error(request, "Author not found.")
#                 return redirect('authors:get-authors')

#             quotes_data = self.fetch_author_quotes(author_slug, page_number)
#             quotes = quotes_data.get('results', [])
#             count = quotes_data.get('count', 0)

#             next_page_url, previous_page_url = self.build_pagination_urls(request, quotes_data, author_slug)

#             context = {
#                 'author': author_data,
#                 'quotes': quotes,
#                 'count': count,
#                 'start_index': start_index,
#                 'page_number': page_number,
#                 'next_page_url': next_page_url,
#                 'previous_page_url': previous_page_url,
#                 'search_query': search_query,
#             }

#             return self.render_htmx_or_full_quotes(request, context)

#         except Exception as e:
#             logger.error(f"Error fetching author data: {str(e)}")
#             messages.error(request, "An error occurred while fetching author data.")
#             return redirect('authors:get-authors')
  
 
class AddAuthorView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'add_author.html'


    def get_success_url(self):
        # Redirect to the detail page of the newly created author
        return reverse_lazy('authors:get-author', kwargs={'slug': self.object.slug})
    # fields = '__all__'
  

  
class UpdateAuthorView(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'update_author.html'
    # fields = '__all__'  
    def get_success_url(self):
        # Redirect to the detail page of the newly created author
        return reverse_lazy('authors:get-author', kwargs={'slug': self.object.slug})
  
class DeleteAuthorView(DeleteView):
    model = Author
    # form_class = QuoteForm
    template_name = 'delete_author.html'
    success_url = reverse_lazy('author:get-authors')
    # fields = '__all__'  


def search_authors(request):
    query = request.GET.get('q', '')
    

    # Check if the query has a minimum length of 2 characters
    if len(query) >= 2:
        print(f"Received query: {query}")

        # Use Q objects to construct a complex OR query
        authors = Author.objects.filter(
            # Q(particul__iexact=query.strip()) |   
            # Q(nickname__unaccent__icontains=query) |
            # Q(last_name__unaccent__icontains=query) |
            # Q(first_name__unaccent__icontains=query) |
            # Q(middle_name__unaccent__icontains=query) 

            Q(fullname__unaccent__icontains=query)
        )


        # # Retrieve translated author names ?
        # translated_names = {}
        # for author in authors:
        #     translated_names[author.id] = author.get_translation(language_code='en')  # Replace 'en' with the desired language code

ubiquote/persons/authors/templates/add_author.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Add an author" %}{% endblock %}
{% block meta_decription %}{% translate "Add an author" %} - {% endblock %}

{% block body %}
{% if user.is_authenticated %}
    <h1>{% translate "Add an author" %}</h1>


    <form method="POST" class="form-control" enctype="multipart/form-data"> 

        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-secondary">{% translate "Post" %}</button>

    </form>

    <p></p>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  


    {% endblock %}  

ubiquote/persons/authors/templates/author_list.html
{% load static %}
{% load i18n %}

{% load translated_author %}
{% load highlight %}

{% comment %}  {% load get_item %}  {% endcomment %} 



        {% if search_query and page_number == 1 %}
          <li>{{ count }} results for "{{ search_query }}"</li>
          {% else %}
        {% endif %}

        {% for author in authors %}

          <!-- Trigger pagination/infinite scroll for loading more authors -->        
          {% if forloop.last and next_page_url %}

              <li class="list-group-item"
                hx-get="{% url 'authors:get-authors' %}?page={{ page_number|add:1 }}{% if search_query %}&q={{ search_query }}{% endif %}" 
                hx-trigger="revealed" 
                hx-swap="afterend" 
                hx-target="this">
                
            {% else %}
              <li class="list-group-item">
          {% endif %}
                <a href="{% url 'authors:get-author' author.slug %}" class="link-offset-2 link-underline link-underline-opacity-10">

                  {% comment %}

                  {{ author.display_name }} {% endcomment %}

                  {{ author|translated_name|highlight_search:search_query|safe }} ({{ author.quote_count }} quotes)

                </a>
             </li>          

        {% endfor %}
      <!-- </ol> -->


{% if not authors %}
  <li>Try a different search or explore our collection!</li>
{% endif %}

ubiquote/persons/authors/templates/delete_author.html
{% extends 'base.html' %}

{% block title %}Delete {{ author }} {% endblock %}
{% block meta_decription %}{{ author }} - {% endblock %}

{% block body %}

{% if user.is_authenticated and user.is_superuser %}

    <h1>Delete {{ author }}</h1>

    <!-- <p>{{ quote.text|safe }}</p> -->

    <form method="POST" class="form-control"> 

        {% csrf_token %}


        <button class="btn btn-secondary">Delete</button>

    </form>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  


    {% endblock %}  

ubiquote/persons/authors/templates/get_author.html
{% extends 'layout_three_column.html' %}

{% block title %}
{{ author.fullname }} 
{% endblock %}

{% block meta_decription %}
{{ author.lastname }}
{% endblock %}

{% block content %}

{% comment%}   
{% endcomment%}   
    {% include "partials/author_card.html" %}     

    {% include "partials/quotes_cards.html" %}


{% endblock %}  

ubiquote/persons/authors/templates/get_authors.html
{% extends 'layout_three_column.html' %}

{% load i18n %}

{% block title %}{{ count }} Authors{% endblock %}
{% block meta_decription %}All the authors{% endblock %}

{% block content %}
    <!-- <h1>Authors</h1> -->

    <!-- <p>{{ count }} authors available in the database</p> -->


   
    {% include 'partials/search_authors.html' %}     



    <!-- <div class="card mt-3"> -->
        <!-- <p> {{ count }} auteurs</p>  -->
     
        <ul id="results" class="list-group col-md" >


            {% include 'partials/authors_cards.html' %}
        </ul>   
    <!-- </div> -->

    {% if user.is_superuser %} 
    <a href="{% url 'authors:add-author' %}" class="link-offset-2 link-underline link-underline-opacity-10">{% translate "Add author" %}</a>
    {% endif %}    


{% endblock %}  

ubiquote/persons/authors/templates/update_author.html
{% extends 'base.html' %}

{% block title %}Edit user {{ user }}{% endblock %}
{% block meta_decription %}{{ quote }} - {% endblock %}

{% block body %}

{% if user.is_authenticated %}
    <h1>Edit user {{ user }}</h1>


    <form method="POST" class="form-control"> 

        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-secondary">Update</button>

    </form>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  

    {% endblock %}  