ubiquote/api/urls.py
from django.urls import path
from . import mixins, views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,

)

app_name = 'api'

urlpatterns = [
    
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),   
    path('token/refresh-session/', mixins.RefreshTokenView.as_view(), name='token-refresh-session'),
    
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),     
    
    path("", views.HomeQuotesAPIView.as_view(), name="home-api-view"),
    
    

    
    path("categories/", views.CategoriesAPIView.as_view(), name="categories-list-api-view"),
    path("category/<str:slug>/", views.CategoryAPIView.as_view(), name="category-api-view"),
    
    path("category/<str:slug>/quotes/", views.CategoryQuotesAPIView.as_view(), name="category-quotes-api-view"),        
    
    


    path("users/", views.UsersAPIView.as_view(), name="users-list-api-view"),    
    path("user/<str:slug>/", views.UserAPIView.as_view(), name="user-api-view"),   # User info
    
    path('user/<str:slug>/quotes/', views.UserQuotesContributorAPIView.as_view(), name='user-quotes-contributor-api-view'), # Quote with contributor is user
    
    path('likes/<str:slug>/', views.UserQuotesLikesAPIView.as_view(), name='user-quotes-likes-api-view'),   

    # CRUD operations for quotes
    path("quotes/", views.QuotesAPIView.as_view(), name="quotes-list-api-view"),
    path("quote/<int:id>/", views.QuoteAPIView.as_view(), name="quote-api-view"),    
    
    path('quote/create/', views.QuoteCreateAPIView.as_view(), name='quote-create'),
    path('quote/<int:id>/update/', views.QuoteUpdateAPIView.as_view(), name='quote-update'),
    path('quote/<int:id>/delete/', views.QuoteDeleteAPIView.as_view(), name='quote-delete'),

    # CRUD operations for authors
    path("authors/", views.AuthorsAPIView.as_view(), name="authors-list-api-view"),
    path("author/<str:slug>/", views.AuthorAPIView.as_view(), name="author-api-view"),        
    path('author/quotes/<str:slug>/', views.AuthorQuotesAPIView.as_view(), name='author-quotes-api-view'),    
    
    path('author/create/', views.AuthorCreateAPIView.as_view(), name='author-create'),
    path('author/<str:slug>/update/', views.AuthorUpdateAPIView.as_view(), name='author-update'),
    path('author/<str:slug>/delete/', views.AuthorDeleteAPIView.as_view(), name='author-delete'),
    
    # path("quote/upload-image/", views.TemporaryImageUploadView.as_view(), name="upload_temp_image"),
    
    
    # path('quote/like/<int:id>/', views.QuotesLikesAPIView.as_view(), name='like-quote'),    
    
    # path('quote/like/<int:id>/', like_quote, name='like-quote'),    
       
           
    # path('quote/<int:quote_id>/like/', LikeQuoteAPIView.as_view(), name='like-quote'),

]

ubiquote/persons/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
  
    # path('', include('django.contrib.auth.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    # path('login/', views.ModalLoginView.as_view(), name='login'),    
    path('logout/', views.LogoutView.as_view(), name='logout'),      
    
    path('users/', views.GetUsersView.as_view(), name='get-users'),
    path('user/<str:slug>/', views.GetUserView.as_view(), name='get-user'),
      
    path('update/user/<str:slug>/', views.UpdateUserView.as_view(), name='update-user'),
    path('delete/user/<str:slug>/', views.DeleteUserView.as_view(), name='delete-user'), 
    
    
    path('likes/<str:slug>/', views.GetUserLikesView.as_view(), name='get-user-likes'),        
  
    # path('add/user/', AddUserView.as_view(), name='add-user'),       
    
]

ubiquote/ubiquote/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

from dal import autocomplete
import djhacker
from django import forms


from persons.authors.models import AuthorAutocomplete

from texts.quotes.models import Quote
from persons.authors.models import Author

from django.utils.translation import gettext_lazy as _

app_name = 'ubiquote'



urlpatterns = []

# Optional: expose this route so users can POST lang choices manually (e.g. via a dropdown)
urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
]

# URLs with language prefix — language will be auto-activated
urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),

    # Include your apps — these will get `fr/`, `en/`, etc. prefixes
    re_path(r'', include('texts.urls', namespace='texts')),
    re_path(r'', include('texts.quotes.urls', namespace='quotes')),
    re_path(r'', include('persons.users.urls', namespace='users')),
    re_path(r'', include('persons.authors.urls', namespace='authors')),

    # Optional: include autocomplete if localized
    path(_('author-autocomplete/'), AuthorAutocomplete.as_view(), name='author-autocomplete'),

    # Optional: localize API routes too (only if needed)
    path(_('api/'), include("api.urls")),
)

# Optional: include rosetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls')),
    ]

# Serve media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# urlpatterns = [
#     # path('admin/', admin.site.urls),
#     path(_('admin/'), admin.site.urls),
    
#     path(_('api/'), include("api.urls")),

#     path(
#         r'author-autocomplete/',
#         AuthorAutocomplete.as_view(),
#         name='author-autocomplete',
#     ),
    

    
# ]

# urlpatterns += i18n_patterns (
#     re_path(r'', include('texts.urls', namespace='texts')),
#     re_path(r'', include('texts.quotes.urls', namespace='quotes')),
#     re_path(r'', include('persons.users.urls', namespace='users')),            
#     re_path(r'', include('persons.authors.urls', namespace='authors')),

    
# )

# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
# ]
    
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
#     import debug_toolbar
#     urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns
    

# djhacker.formfield(
#     Quote.author,
#     forms.ModelChoiceField,
#     widget=autocomplete.ModelSelect2(url='ubiquote:author-autocomplete')
#     )

ubiquote/persons/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth import login
from rest_framework_simplejwt.tokens import RefreshToken
from django.http import JsonResponse

from django.urls import reverse, reverse_lazy
from django.db.models import Max

from django.contrib import messages

from django.views import generic
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from .forms import UserCreationForm, UserChangeForm, AuthenticationForm

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from texts.quotes.models import Quote, QuotesLikes
from api.mixins import QuotesFetchingMixin #, TokenRefreshMixin 


from .models import User
from .forms import  UserForm
from django.conf import settings

# from texts.quotes.views import like_quote

from django.contrib.auth import views as auth_views
from django.utils.translation import get_language
import re

import requests

from django.utils.http import url_has_allowed_host_and_scheme
from urllib.parse import urlsplit


class GetUserLikesView(QuotesFetchingMixin,LoginRequiredMixin, ListView):
    template_name = 'get_user_likes.html'
    # api_url = settings.API_URL
    api_url = 'http://127.0.0.1:8000/api' 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context    
    

    def get(self, request, *args, **kwargs):
         

    # if request.user.is_authenticated:
    
        profil_slug = self.kwargs['slug']
        
        page_number = request.GET.get('page', 1)
        search_query = request.GET.get('q', '')
        user = request.user

        # request.session.flush()
        
        # Default to computed start_index if not passed from HTMX
        incoming_start_index = request.GET.get('start_index')
        if incoming_start_index is not None:
            start_index = int(incoming_start_index)
        else:
            # Only for first page or full render
            start_index = 0           
        
    

        # Fetch data for the home view (e.g., recommendations)
        data = self.get_api_data(page_number, endpoint=f'likes/{profil_slug}/')  # Custom endpoint for Likes of user
        
        # 👇 If a JsonResponse or redirect, return early
        if isinstance(data, HttpResponse):
            return data


        # Handle pagination and results
        results = data.get('results', [])
        next_page_url, previous_page_url = self.process_pagination(data, request)
        count = data.get('count', 0)
        
        

        profil_api_url = f'{self.api_url}/user/{profil_slug}/'
        profil_response = requests.get(profil_api_url)

        if profil_response.status_code == 200:
            profil = profil_response.json()

        else:
            profil = []            
        

        context = {
            'quotes': results,  # Keep this as 'quotes' if your template expects it
            'profil': profil,
            'count': count,
            'start_index': start_index,
            'page_number': page_number,
            'next_page_url': next_page_url,
            'previous_page_url': previous_page_url,
            'search_query' : search_query,
        }
        
        # # redirect to landing page if count ==0 (means the session is over)
        # if count==0:
        #     logout(self.request)
        #     return self.render_landing_page(request) 
        
        return self.render_htmx_or_full_quotes(request, context)
    # else:              
    #     return self.render_landing_page(request) 


# def render_landing_page(self, request):
#     """Renders a public landing page for non-authenticated users."""
#     return render(request, 'landing_page.html', {})  # Create `landing.html` 


# class GetUserLikesView(LoginRequiredMixin, ListView):
#     model = Quote
#     context_object_name = 'quotes'  
#     template_name = 'get_user_likes.html'
#     paginate_by = settings.DEFAULT_PAGINATION  # Number of items per page  
    
#     # API URL for quotes list
#     api_url = 'http://127.0.0.1:8000/api'        

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         return context


#     def get(self, request, *args, **kwargs):
#         page_number = request.GET.get('page', 1)
#         profil_slug = self.kwargs['slug']
#         search_query = request.GET.get('q', '')       
            
#         user = request.user
        
#         # Default to computed start_index if not passed from HTMX
#         incoming_start_index = request.GET.get('start_index')
#         if incoming_start_index is not None:
#             start_index = int(incoming_start_index)
#         else:
#             # Only for first page or full render
#             start_index = 0          
                

#         # Adjust API URL to pass pagination and search query
#         likes_api_url = f'{self.api_url}/likes/{profil_slug}/?page={page_number}'
#         # quote_response = requests.get(api_url, headers={'Authorization': f'Token {request.user.auth_token}'})
        
#         # quote_api_url = f'http://127.0.0.1:8000/api/user/{profil.slug}/quotes/?page={page_number}'
#         response = requests.get(likes_api_url)

#         if response.status_code == 200:
#             data = response.json()
#             # print(data)
#             quotes = data.get('results', [])
#             count = data.get('count', 0)             
#             next_page_url = data.get('next')
#             previous_page_url = data.get('previous')            
#         else:
#             quotes = []
#             next_page_url = None
#             previous_page_url = None            

#         lang = request.LANGUAGE_CODE
#         # Replace /api/likes/ with the correct frontend path
#         if next_page_url:
#             next_page_url = next_page_url.replace('/api/', f'/{lang}/')

#         # print(previous_page_url)
#         if previous_page_url:
#             previous_page_url = previous_page_url.replace('/api/', f'/{lang}/')
#         # print(previous_page_url)            

#         profil_api_url = f'{self.api_url}/user/{profil_slug}/'
#         profil_response = requests.get(profil_api_url)

#         if profil_response.status_code == 200:
#             profil = profil_response.json()

#         else:
#             profil = []


#         context = {
#             'profil': profil, 
#             'quotes': quotes,
#             'count': count,
#             'start_index': start_index,            
#             'page_number': page_number,
#             'next_page_url': next_page_url,
#             'previous_page_url': previous_page_url,
#             'search_query': search_query,      
#         }    
        
#         # If it's an HTMX request, return only the quotes part
#         if request.htmx:

#             return render(request, 'partials/quotes_cards.html', context)        

#         return render(request, self.template_name, context)    



class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    # success_url = reverse_lazy('users:login')
    success_url = reverse_lazy('texts:get-home')
    
    
    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)  # Automatically logs the user in
        return redirect(self.success_url) # Redirects to the home page    
    


class LoginView(auth_views.LoginView):
    form_class = AuthenticationForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('texts:get-home')
    EXCEPTION_PATHS = [
        r'^(/..)?/register/?$',  # optional 2-letter lang prefix
    ]

    def form_valid(self, form):
        request = self.request
        user = form.get_user()
        login(request, user)

        # Generate JWT tokens
        refresh = RefreshToken.for_user(user)
        request.session["access_token"] = str(refresh.access_token)
        request.session["refresh_token"] = str(refresh)


        next_url = request.POST.get("next") or request.GET.get("next")
        if not next_url or any(re.match(p, next_url) for p in self.EXCEPTION_PATHS):
            next_url = str(self.success_url)
        else:
            # Only keep the path (removes ?page=..., etc.)
            next_url = urlsplit(next_url).path


        # # Handle HTMX/AJAX login
        # if request.headers.get('HX-Request') or request.headers.get('x-requested-with') == 'XMLHttpRequest':
        #     response = JsonResponse({'success': True})
        #     response['HX-Redirect'] = next_url
        #     return response

        return redirect(next_url)

    def get_template_names(self):
        if self.request.headers.get('HX-Request'):
            return ['registration/modal_login.html']
        return [self.template_name]
    
    

# class ModalLoginView(auth_views.LoginView):
#     def form_valid(self, form):
#         super().form_valid(form)
#         if self.request.headers.get("HX-Request"):
#             return JsonResponse({"success": True}, headers={"HX-Trigger": "loginSuccess"})
#         return super().form_valid(form)

#     def form_invalid(self, form):
#         if self.request.headers.get("HX-Request"):
#             return JsonResponse({"success": False, "errors": form.errors}, status=400)
#         return super().form_invalid(form)    
    
    
class LogoutView(auth_views.LogoutView):
    form_class = AuthenticationForm
    template_name = 'registration/logout.html'
    success_url = reverse_lazy('texts:home')
    
    # def dispatch(self, request, *args, **kwargs):

ubiquote/persons/users/templates/add_user.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Add a user" %}{% endblock %}
{% block meta_decription %}{% translate "Add a quote" %} - {% endblock %}

{% block body %}
{% if user.is_authenticated and user.is_superuser %}
    <h1>{% translate "Add a user" %}</h1>


    <form method="POST" class="form-control" enctype="multipart/form-data"> 

        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-secondary">{% translate "Add user" %}</button>

    </form>

    <p></p>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  


    {% endblock %}  

ubiquote/persons/users/templates/delete_user.html
{% extends 'base.html' %}

{% block title %}Delete an author{% endblock %}
{% block meta_decription %}{{ author }} - {% endblock %}

{% block body %}

{% if user.is_authenticated and user.is_superuser %}

    <h1>Delete an author</h1>

    <!-- <p>{{ quote.text|safe }}</p> -->

    <form method="POST" class="form-control"> 

        {% csrf_token %}


        <button class="btn btn-secondary">Delete</button>

    </form>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  


    {% endblock %}  

ubiquote/persons/users/templates/get_user.html
{% extends 'layout_three_column.html' %}
{% block title %}{{ profil.username }} profil page {% endblock %}

{% block meta_decription %}{{ profil}} - {% endblock %}

{% block content %}




{% comment%}


    <h1>{{ profil.username|default_if_none:"" }}</h1>

    <h2>{{ profil.first_name|default_if_none:""  }} {{ profil.middle_name|default_if_none:"" }} {{ profil.last_name|default_if_none:"" }}</h2>

    {% if profil.avatar.url is not None %}
      <img src="{{ profil.avatar.url }}" class="rounded-circle">
    {% endif %}




    <!-- <p>{{ quotes.count }} quotes published.</p>     -->

    {% if profil.date_birth is not None %}
      <p>date_birth : {{ profil.date_birth|date:"d M Y"|safe }} </p>
    {% endif %}      

    {% if profil.date_death is not None %}
      <p>date_death : {{ profil.date_death|date:"d M Y"|safe }}</p>
    {% endif %}         
    
    {% if profil.sex is not None %}    
      <p>sex : {{ profil.sex|safe }}</p>
    {% endif %}

    {% if profil.nationality is not None %}   
      <p>nationality :  {{ profil.nationality|safe }}</p>
    {% endif %}

    <p>date_created : {{ profil.date_created|date:"d M Y à G:i"|safe }}</p>
    <p>date_updated : {{ profil.date_updated|date:"d M Y à G:i"|safe }}</p>

    <p>
      <a href="{{ profil.twitter_url|safe }}" class="link-offset-2 link-underline link-underline-opacity-10">
      twitter
      </a>
    </p>

    Total contribution : {{ count }}
    


    {% if user.is_authenticated and profil.slug == user.slug or user.is_superuser  %}
      <a href="{% url 'users:update-user' user.slug %}" class="link-offset-2 link-underline link-underline-opacity-10">Update user</a>
      <a href="{% url 'users:delete-user' user.slug %}" class="link-offset-2 link-underline link-underline-opacity-10">Delete user</a>      
    {% endif %}


{% endcomment %}

    {% include "partials/quotes_cards.html" %}

{% endblock %}  

ubiquote/persons/users/templates/get_user_likes.html
{% extends 'layout_three_column.html' %}
{% load i18n %}

{% block title %}Likes of {{ profil.username }}{% endblock %}
{% block meta_decription %}List of my likes{% endblock %}

{% block content %}

  <h1>{% translate "Likes of" %} {{ profil.username }}</h1>
  <p>{{ count }} quotes liked by {{ profil.username }}</p>  


    {% include "partials/quotes_cards.html" %}    

{% endblock %}  

ubiquote/persons/users/templates/get_users.html
{% extends 'layout_three_column.html' %}

{% block title %}Users{% endblock %}
{% block meta_decription %}All the users{% endblock %}

{% block content %}

    <h1>Users</h1>
    <p>{{ users.count }} users available in the database</p>    
    <ul>
    {% for user in users %}
    <li>

      <a href="{% url 'users:get-user' user.slug  %}" class="link-offset-2 link-underline link-underline-opacity-10">

        {{ user.username|safe }}
    </a>

    </li>      
    {% endfor %}
    </ul>

    {% endblock %}  

ubiquote/persons/users/templates/update_user.html
{% extends 'base.html' %}

{% block title %}Edit a user {% endblock %}
{% block meta_decription %}{{ user }} - {% endblock %}

{% block body %}

{% if user.is_authenticated and user.is_superuser %}
    <h1>Edit a author</h1>


    <form method="POST" class="form-control"> 

        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-secondary">Update</button>

    </form>

{% else %}
    <p>You are not allowed here</p>
{% endif %}  

    {% endblock %}  